public with sharing class Minha_Org_do_Cruso_Salesforce_Apex {
    public Minha_Org_do_Cruso_Salesforce_Apex() {
      /* 
        Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o SENHOR 
        teu Deus é contigo, por onde quer que andares. (Josué 1:9)

        E não cansemos de fazer bem, porque a seu tempo ceifaremos, se não houvermos desfalecido. 
        (Gálatas 6:9)
      */
      System.debug('Ola Mundo! Hello world!');
      //  Essa funcionalidade vai trazer pra nós um valor.
    }
}
